#include "datatype.h"
void doMenuTeacher();
void menuTeacher();
void addTeacher();
void menu();
void admin();
void addStudent();
void displayStudents();
void searchStudent();
void admin();
void arrangeStudent();
void arrangeId();